adb shell am force-stop system
adb shell am force-stop com.catchingnow.icebox
adb shell am force-stop com.ss.android.ugc.aweme
adb shell am force-stop com.tencent.mm
adb shell am force-stop com.milink.service
adb shell am force-stop com.xiaomi.market
adb shell am force-stop com.xiaomi.xmsf
adb shell am force-stop com.tencent.mobileqq
adb shell am force-stop com.google.android.gms
adb shell am force-stop com.mi.health
adb shell am force-stop com.xiaomi.aicr
adb shell am force-stop com.catchingnow.np:Service
adb shell am force-stop com.miui.gallery
adb shell am force-stop com.miui.home
adb shell am force-stop com.android.vending
adb shell am force-stop com.tencent.mm:push
adb shell am force-stop com.android.mms
adb shell am force-stop com.baidu.input
adb shell am force-stop com.tencent.mobileqq:MSF
adb shell am force-stop com.android.htmlviewer
adb shell am force-stop com.miui.guardprovider
adb shell am force-stop com.miui.personalassistant
adb shell am force-stop com.android.quicksearchbox
adb shell am force-stop com.mi.health:device
adb shell am force-stop com.milink.service.persistent
adb shell am force-stop com.android.vending:background
adb shell am force-stop com.mi.health:widgetProvider
adb shell am force-stop com.kugou.android.lite:widgetProvider
adb shell am force-stop com.miui.miwallpaper
adb shell am force-stop com.xiaomi.market:widgetProvider
adb shell am force-stop android.process.media
adb shell am force-stop com.wpengapp.lightstart:service
adb shell am force-stop com.google.android.documentsui
adb shell am force-stop com.android.permissioncontroller
adb shell am force-stop com.xiaomi.aicr:actionprovider
adb shell am force-stop com.lbe.security.miui
adb shell am force-stop com.miui.systemAdSolution
adb shell am force-stop com.xiaomi.xmsf:kit6
adb shell am force-stop com.xiaomi.metoknlp
adb shell am force-stop com.miui.screenrecorder
adb shell am force-stop com.android.providers.media.module
adb shell am force-stop com.xiaomi.vtcamera
adb shell am force-stop com.xiaomi.xmsf:persistent
adb shell am force-stop com.android.camera
adb shell am force-stop com.google.android.gms.unstable
adb shell am force-stop com.milink.crossdeviceservice
adb shell am force-stop com.miui.misound
adb shell am force-stop com.android.mms:mms_service
adb shell am force-stop com.xiaomi.xmsf:kit7
adb shell am force-stop com.google.android.gms:snet
adb shell am force-stop android.process.acore
adb shell am force-stop com.milink.service:ui
adb shell am force-stop com.miui.cloudservice
adb shell am force-stop com.google.android.gms.persistent
adb shell am force-stop com.miui.hybrid
adb shell am force-stop com.xiaomi.account
adb shell am force-stop android.ext.services
adb shell am force-stop com.xiaomi.xmsf:services
adb shell am force-stop com.xiaomi.xmsfkeeper
adb shell am force-stop com.tencent.soter.soterserver
adb shell am force-stop org.ifaa.aidl.manager
adb shell am force-stop com.android.htmlviewer:remote
adb shell am force-stop com.miui.voiceassist:core
adb shell am force-stop com.catchingnow.icebox:Service
adb shell am force-stop com.miui.core
adb shell am force-stop com.milink.service:core
adb shell am force-stop com.android.calendar
adb shell am force-stop com.milink.runtime
adb shell am force-stop com.miui.analytics
adb shell am force-stop com.miui.micloudsync
adb shell am force-stop com.milink.service:audio
adb shell am force-stop com.xiaomi.simactivate.service
adb shell am force-stop com.milink.service:provider
adb shell am force-stop com.google.android.webview:webview_service
adb shell am force-stop com.android.deskclock
adb shell am force-stop com.google.android.webview:webview_apk
adb shell am force-stop com.android.providers.calendar
adb shell am force-stop com.miui.phrase
adb shell am force-stop com.xiaomi.mibrain.speech
adb shell am force-stop com.miui.cloudbackup
adb shell am force-stop com.xiaomi.aicr:cognitionService
adb shell am force-stop com.android.externalstorage
adb shell am force-stop com.xiaomi.aicr:coreService
adb shell am force-stop com.miui.contentextension